Repository CSwala/CSwala-android, pull requests merged in 2021-03, with the labels that each got.

#75 Contributors
  README.md
Labels: Level1, documentation, gssoc21

#80 Add Profile and Community Fragment.
  app/src/main/java/com/cswala/cswala/CommunityFragment.java
  app/src/main/java/com/cswala/cswala/MainActivity.java
  app/src/main/java/com/cswala/cswala/ProfileFragment.java
  app/src/main/res/layout/fragment_community.xml
  app/src/main/res/layout/fragment_profile.xml
Labels: Level2, enhancement, gssoc21

#83 Fix #68 Added tech stack
  README.md
Labels: Level0, documentation, gssoc21

#85 Add Explore Fragment
  app/src/main/java/com/cswala/cswala/ExploreFragment.java
  app/src/main/java/com/cswala/cswala/MainActivity.java
  app/src/main/res/layout/fragment_explore.xml
Labels: Level2, enhancement, gssoc21

#106 Fix #67 and #98: Replace logout textview and fix Google sign-in bug
  app/src/main/java/com/cswala/cswala/Activities/LoginActivity.java
  app/src/main/java/com/cswala/cswala/Fragments/ProfileFragment.java
  app/src/main/java/com/cswala/cswala/MainActivity.java
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_community.xml
  app/src/main/res/layout/fragment_explore.xml
  app/src/main/res/layout/fragment_job_hunt.xml
  app/src/main/res/layout/fragment_news.xml
  app/src/main/res/layout/fragment_profile.xml
Labels: Level3, gssoc21

#118 update contributing.md
  CONTRIBUTING.md
Labels: Level1, documentation, gssoc21

#110 created ExploreFragment and it's logic part.
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/cswala/cswala/Activities/TechDataActivity.java
  app/src/main/java/com/cswala/cswala/Adapters/TechListAdapter.java
  app/src/main/java/com/cswala/cswala/Adapters/techItemClicked.java
  app/src/main/java/com/cswala/cswala/Fragments/ExploreFragment.java
  app/src/main/java/com/cswala/cswala/MainActivity.java
  app/src/main/java/com/cswala/cswala/Models/TechListElement.java
  app/src/main/java/com/cswala/cswala/utils/IntentHelper.java
  app/src/main/res/drawable/search_background.xml
  app/src/main/res/layout/activity_tech_data.xml
  app/src/main/res/layout/fragment_explore.xml
  app/src/main/res/layout/tech_list_element.xml
  app/src/main/res/values/strings.xml
Labels: Level3, enhancement, gssoc21

#135 #115 Implement HackFeed Fragment Done Fully GSSOC21
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/cswala/cswala/Adapters/LatestNewsAdapter.java
  app/src/main/java/com/cswala/cswala/Fragments/LatestNewsFragment.java
  app/src/main/java/com/cswala/cswala/Fragments/NewsEventsFragment.java
  app/src/main/java/com/cswala/cswala/Fragments/NewsFragment.java
  app/src/main/res/drawable/rounded_corners_button.xml
  app/src/main/res/layout/fragment_latest_news.xml
  app/src/main/res/layout/fragment_news.xml
  app/src/main/res/layout/fragment_news_events.xml
  app/src/main/res/layout/latest_news_element.xml
  app/src/main/res/values/strings.xml
Labels: Level3, enhancement, gssoc21

#141 improved splash screen
  app/build.gradle
  app/src/main/res/anim/text_anim.xml
Labels: Level0, gssoc21
