Repository CSwala/CSwala-android, pull requests merged in 2021-04, with the labels that each got.

#145 #117 Add Link Preview in Tech Data Activity and Webview also opening in the app only.
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/cswala/cswala/Activities/LoginActivity.java
  app/src/main/java/com/cswala/cswala/Activities/TechDataActivity.java
  app/src/main/java/com/cswala/cswala/Activities/WebActivity.java
  app/src/main/java/com/cswala/cswala/Adapters/WebAdapter.java
  app/src/main/java/com/cswala/cswala/Models/WebModel.java
  app/src/main/java/com/cswala/cswala/utils/IntentHelper.java
  app/src/main/res/layout/activity_tech_data.xml
  app/src/main/res/layout/activity_web.xml
  app/src/main/res/layout/small_view.xml
Labels: Level3, enhancement, gssoc21

#146 issue#143
  app/src/main/res/layout/fragment_profile.xml
Labels: Level2, bug, gssoc21

#150 Fix #92: Add landscape variation to main activity
  app/src/main/res/drawable/navbar_background_land.xml
  app/src/main/res/layout-land/activity_main.xml
Labels: Level2, gssoc21

#149 Fix part of #116
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/cswala/cswala/Adapters/MessageAdapter.java
  app/src/main/java/com/cswala/cswala/Fragments/CommunityFragment.java
  app/src/main/java/com/cswala/cswala/MainActivity.java
  app/src/main/java/com/cswala/cswala/Models/Message.java
  app/src/main/java/com/cswala/cswala/observer/ScrollToBottomObserver.java
  app/src/main/java/com/cswala/cswala/utils/MessageListener.java
  app/src/main/java/com/cswala/cswala/viewholders/MessageHolder.java
  app/src/main/res/drawable/avatar.xml
  app/src/main/res/drawable/ic_baseline_insert_emoticon_24.xml
  app/src/main/res/drawable/ic_baseline_send_24.xml
  app/src/main/res/drawable/rounded_corner.xml
  app/src/main/res/drawable/send_circle.xml
  app/src/main/res/layout/fragment_community.xml
  app/src/main/res/layout/message_item_view.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
  gradle/wrapper/gradle-wrapper.properties
Labels: Level3, gssoc21

#153 Fix #109: Add network check on login
  app/src/main/java/com/cswala/cswala/Activities/LoginActivity.java
  app/src/main/java/com/cswala/cswala/Activities/LoginWithEmail.java
  app/src/main/java/com/cswala/cswala/Activities/Register.java
  app/src/main/java/com/cswala/cswala/MainActivity.java
  app/src/main/java/com/cswala/cswala/utils/NetworkConnection.java
  app/src/main/res/values/strings.xml
Labels: Level2, gssoc21

#151 Fixes #111 Added edit profile option
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/cswala/cswala/Activities/User.java
  app/src/main/java/com/cswala/cswala/Activities/editProfile.java
  app/src/main/java/com/cswala/cswala/Fragments/ProfileFragment.java
  app/src/main/res/layout/activity_edit_profile.xml
  app/src/main/res/layout/color_spinner_layout.xml
  app/src/main/res/layout/fragment_profile.xml
  app/src/main/res/layout/spinner_dropdown_layout.xml
Labels: Level3, enhancement, gssoc21

#156 Improved UI.
  app/src/main/res/layout/latest_news_element.xml
Labels: Level0, gssoc21

#162 Fix #144: Add exit dialog
  app/src/main/java/com/cswala/cswala/Activities/LoginActivity.java
  app/src/main/java/com/cswala/cswala/MainActivity.java
Labels: Level1, gssoc21

#161 Fix part 2 of #139: Add swipe functionality
  app/src/main/java/com/cswala/cswala/Adapters/LatestNewsAndEventsPageAdapter.java
  app/src/main/java/com/cswala/cswala/Fragments/NewsFragment.java
  app/src/main/res/layout/fragment_news.xml
Labels: Level2, gssoc21

#169 Landscape variation in Login activity.
  app/src/main/res/layout-land/activity_login.xml
Labels: Level1, gssoc21

#179 bug fixed (issue-178)
  app/src/main/java/com/cswala/cswala/Fragments/ExploreFragment.java
Labels: Level2, gssoc21
